const catC = require('../controllers/categories.c');
const app = require('express');
const fs = require('fs');
const path = require('path');
const proM = require('../model/product.m');
const router = app.Router();
router.post('/:CatID/delete', catC.delete).post(catC.delete);
router.post('/:CatID/edit', catC.edit).post(catC.edit);
router.post('/:CatID/add-product', catC.addProduct).post(catC.addProduct);
router.get('/:CatID', catC.render).post(catC.render);
module.exports = router;